spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eventmanagement?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        "[format_sql]": true
        "[dialect]": org.hibernate.dialect.MySQLDialect
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
  mail:
    host: smtp.gmail.com
    port: 587
    username: dwanmohite@gmail.com
    password: oylg eeyt veiv cpzi
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

server:
  port: 8081
  servlet:
    context-path: /api

# JWT configuration
app:
  jwt:
    secret: WXsq0b1BHv8p9xjlpMRUBwtaytKatF63D43T5+xzLEc6qFsSX7MEKUo/73mbFsPvUYRJ1qTsZzpfQo2sKGK1/Q==
    expiration-ms: 86400000 # 24 hours

# Razorpay configuration
razorpay:
  key:
    id: rzp_test_z2eDnVHW1PyPqG
    secret: BwIlCk9cfaEALxbZaTydZ1mi

# Logging configuration
logging:
  level:
    "[org.springframework.web]": INFO
    "[org.hibernate]": INFO
    "[com.example.bookverse]": DEBUG 