spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eventmanagement?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        "[dialect]": org.hibernate.dialect.MySQLDialect
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME:your-email@gmail.com}
    password: ${EMAIL_PASSWORD:your-app-password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

server:
  port: 8080
  servlet:
    context-path: /api

# JWT configuration
app:
  jwt:
    secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=
    expiration-ms: 86400000 # 24 hours

# Razorpay configuration
razorpay:
  key:
    id: rzp_test_yourkeyhere
    secret: yoursecrethere

# Logging configuration
logging:
  level:
    "[org.springframework.web]": INFO
    "[org.hibernate]": INFO
    "[com.example.bookverse]": DEBUG 